language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# Python requests isn't found using Pip
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-requests    

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  
script:
  - ./benchmark.py 

virtualenv:
  system_site_packages: true
