language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  
# test benchmark.py
script:
  - python3 benchmark.py https://graph.irail.be/sncb/connections -n 10 -i -o results.csv
